### PR TITLE
fix: Show Processor Telemetry Types 

### PR DESCRIPTION
**Pull request by dsvanlani**
### Proposed Change
- Query for telemetry types and pass them through the Resource Button in the Processor Select View.

image

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

### CODE REVIEW

**Review by andykellr — APPROVED** [review]
I think add/delete attribute is logs only, but we should confirm with @jsirianni

**Comment by jsirianni** [comment]
> I think add/delete attribute is logs only, but we should confirm with @jsirianni

It is. I have a fix coming in a PR. I think it is fine for now.

**Comment by jsirianni** [comment]
https://github.com/observIQ/bindplane-op/pull/228

**Comment by dsvanlani** [comment]
Working correctly after merging Joes fix from main.
image

**Pull request merged**
