### PR TITLE
feat: bindplanectl get resources

### PR DESCRIPTION
**Pull request by andykellr**
### Proposed Change
Useful for export / import of all BindPlane resources.
```
bindplanectl get resources
bindplanectl get resources -o yaml
bindplanectl get resources -o yaml | bindplanectl apply -f -
```

##### Checklist
- [x] Changes are tested
- [ ] CI has passed

### CODE REVIEW

**Review by dehaansa — APPROVED** [review]
imo it could/should default to yaml, but -o yaml isn't hard to type.

**Comment by jsirianni** [comment]
This is working for the most part. There are some ordering concerns
1. Backup system A with `get resources`
2. Deploy to another system (after switching my profile) `apply -f`
3. Notice that not all configs made it in, but components did.
4. Re-apply
5. Now all configs exist

**Comment by dsvanlani** [comment]
This is working well but I'm getting strange behavior when I apply the resources I saved (all of the SourceTypes, ProcessorTypes, and DestinationTypes) it says they are "configured" when I apply them:

```
SourceType couchbase configured
SourceType couchdb configured
SourceType csv configured
SourceType elasticsearch configured
...
```

But if i just do `bp get source-type macos | bp apply -` I get status unchanged:
```
bpdev get source-type macos -o yaml | bp apply -
SourceType macOS unchanged
```

I can't really explain this.

**Review by dsvanlani — APPROVED** [review]

**Comment by andykellr** [comment]
I'm going to tweak the iteration order so that it can be applied in one pass to an empty server. I'm also going to figure out why it says `configured`. I'll come back to this soon.

**Comment by andykellr** [comment]
Ok, I'm done with tweaks. @dsvanlani and @jsirianni can you test again?

**Review by jsirianni — APPROVED** [review]

**Pull request merged**
