### PR TITLE
feat: Update Agent

### PR DESCRIPTION
**Pull request by andykellr**
### Proposed Change
Provides the ability to upgrade an agent using the CLI or UI.

Resolves observiq/iris#1005

##### Checklist
- [x] Changes are tested
- [x] CI has passed

### CODE REVIEW

**Comment by andykellr** [comment]
@dsvanlani  The Agents Table upgrade worked really well except it was left in a state where I am still offered to delete 2 disconnected agents but none are selected.
Screen Shot 2022-08-07 at 11 46 38 PM

**Review by dsvanlani — APPROVED** [review]
Working great for me.

**Comment by jsirianni** [comment]
Would it be possible to format the output so that it can be used with awk in an easy way?

```
NAME                          	TYPE                   	VERSION	PUBLIC	RELEASE DATE	RELEASE NOTES                                                           
observiq-otel-collector-v1.6.1	observiq-otel-collector	v1.6.1 	true  	Aug 05, 2022	https://github.com/observIQ/observiq-otel-collector/releases/tag/v1.6.1	
observiq-otel-collector-v1.6.0	observiq-otel-collector	v1.6.0 	true  	Aug 05, 2022	https://github.com/observIQ/observiq-otel-collector/releases/tag/v1.6.0	
```

Can `RELEASE DATE` be renamed to something that is one word? `RELEASE_DATE` or RELEASEDATE? Same with release notes. This would also mean reformatting the date values to something else. `08052022`, `08-05-2022`.

This would be useful if printing a column with awk. 
```bash
bindplanectl get agent-versions | awk '{print $7}'
```

**Review by jsirianni — CHANGES_REQUESTED** [review]
I am getting errors when upgrading a Linux agent from v1.6.0 to v1.6.1

```
{"level":"info","ts":"2022-08-08T13:09:10.302-0400","logger":"opamp","caller":"observiq/observiq_client.go:455","msg":"Package update started","AllPackagesHash":"76312e362e31","package":"observiq-otel-collector"}

{"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"service/managed.go:85","msg":"Shutting down collector"}

{"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"service/collector.go:162","msg":"Received shutdown request"}

{"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"service/collector.go:231","msg":"Starting shutdown..."}

{"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"pipelines/pipelines.go:118","msg":"Stopping receivers..."}

{"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"pipelines/pipelines.go:125","msg":"Stopping processors..."}

{"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"pipelines/pipelines.go:132","msg":"Stopping exporters..."}

{"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"extensions/extensions.go:56","msg":"Stopping extensions..."}

{"level":"error","ts":"2022-08-08T13:09:12.088-0400","logger":"opamp","caller":"internal/wsreceiver.go:50","msg":"Unexpected error while receiving: read tcp 10.99.1.10:42904->10.99.1.10:3001: use of closed network connection","stacktrace":"github.com/open-telemetry/opamp-go/client/internal.(*wsReceiver).ReceiverLoop\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/wsreceiver.go:50\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runOneCycle\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:235\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runUntilStopped\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:257\ngithub.com/open-telemetry/opamp-go/client/internal.(*ClientCommon).StartConnectAndRun.func1\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/clientcommon.go:162"}
{"level":"error","ts":"2022-08-08T13:09:12.088-0400","logger":"opamp","caller":"observiq/observiq_client.go:265","msg":"Failed to connect to server","error":"dial tcp 10.99.1.10:3001: operation was canceled","stacktrace":"github.com/observiq/observiq-otel-collector/opamp/observiq.(*Client).onConnectFailedHandler\n\t/home/runner/work/observiq-otel-collector/observiq-otel-collector/opamp/observiq/observiq_client.go:265\ngithub.com/open-telemetry/opamp-go/client/types.CallbacksStruct.OnConnectFailed\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/types/callbacks.go:146\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).tryConnectOnce\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:120\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).ensureConnected\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:158\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runOneCycle\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:195\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runUntilStopped\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:257\ngithub.com/open-telemetry/opamp-go/client/internal.(*ClientCommon).StartConnectAndRun.func1\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/clientcommon.go:162"}

{"level":"error","ts":"2022-08-08T13:09:12.088-0400","logger":"opamp","caller":"client/wsclient.go:163","msg":"Connection failed (dial tcp 10.99.1.10:3001: operation was canceled), will retry.","stacktrace":"github.com/open-telemetry/opamp-go/client.(*wsClient).ensureConnected\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:163\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runOneCycle\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:195\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runUntilStopped\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:257\ngithub.com/open-telemetry/opamp-go/client/internal.(*ClientCommon).StartConnectAndRun.func1\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/clientcommon.go:162"}
```

**Comment by andykellr** [comment]
> I am getting errors when upgrading a Linux agent from v1.6.0 to v1.6.1
> 
> ```
> {"level":"info","ts":"2022-08-08T13:09:10.302-0400","logger":"opamp","caller":"observiq/observiq_client.go:455","msg":"Package update started","AllPackagesHash":"76312e362e31","package":"observiq-otel-collector"}
> 
> {"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"service/managed.go:85","msg":"Shutting down collector"}
> 
> {"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"service/collector.go:162","msg":"Received shutdown request"}
> 
> {"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"service/collector.go:231","msg":"Starting shutdown..."}
> 
> {"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"pipelines/pipelines.go:118","msg":"Stopping receivers..."}
> 
> {"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"pipelines/pipelines.go:125","msg":"Stopping processors..."}
> 
> {"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"pipelines/pipelines.go:132","msg":"Stopping exporters..."}
> 
> {"level":"info","ts":"2022-08-08T13:09:12.088-0400","caller":"extensions/extensions.go:56","msg":"Stopping extensions..."}
> 
> {"level":"error","ts":"2022-08-08T13:09:12.088-0400","logger":"opamp","caller":"internal/wsreceiver.go:50","msg":"Unexpected error while receiving: read tcp 10.99.1.10:42904->10.99.1.10:3001: use of closed network connection","stacktrace":"github.com/open-telemetry/opamp-go/client/internal.(*wsReceiver).ReceiverLoop\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/wsreceiver.go:50\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runOneCycle\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:235\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runUntilStopped\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:257\ngithub.com/open-telemetry/opamp-go/client/internal.(*ClientCommon).StartConnectAndRun.func1\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/clientcommon.go:162"}
> {"level":"error","ts":"2022-08-08T13:09:12.088-0400","logger":"opamp","caller":"observiq/observiq_client.go:265","msg":"Failed to connect to server","error":"dial tcp 10.99.1.10:3001: operation was canceled","stacktrace":"github.com/observiq/observiq-otel-collector/opamp/observiq.(*Client).onConnectFailedHandler\n\t/home/runner/work/observiq-otel-collector/observiq-otel-collector/opamp/observiq/observiq_client.go:265\ngithub.com/open-telemetry/opamp-go/client/types.CallbacksStruct.OnConnectFailed\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/types/callbacks.go:146\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).tryConnectOnce\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:120\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).ensureConnected\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:158\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runOneCycle\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:195\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runUntilStopped\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:257\ngithub.com/open-telemetry/opamp-go/client/internal.(*ClientCommon).StartConnectAndRun.func1\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/clientcommon.go:162"}
> 
> {"level":"error","ts":"2022-08-08T13:09:12.088-0400","logger":"opamp","caller":"client/wsclient.go:163","msg":"Connection failed (dial tcp 10.99.1.10:3001: operation was canceled), will retry.","stacktrace":"github.com/open-telemetry/opamp-go/client.(*wsClient).ensureConnected\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:163\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runOneCycle\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:195\ngithub.com/open-telemetry/opamp-go/client.(*wsClient).runUntilStopped\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/wsclient.go:257\ngithub.com/open-telemetry/opamp-go/client/internal.(*ClientCommon).StartConnectAndRun.func1\n\t/home/runner/go/pkg/mod/github.com/open-telemetry/opamp-go@v0.2.0/client/internal/clientcommon.go:162"}
> ```

These errors are normal on shutdown (fixed by https://github.com/open-telemetry/opamp-go/pull/113 but we have not updated). What state is the collector in after that?

**Comment by andykellr** [comment]
> Would it be possible to format the output so that it can be used with awk in an easy way?
> 
> ```
> NAME                          	TYPE                   	VERSION	PUBLIC	RELEASE DATE	RELEASE NOTES                                                           
> observiq-otel-collector-v1.6.1	observiq-otel-collector	v1.6.1 	true  	Aug 05, 2022	https://github.com/observIQ/observiq-otel-collector/releases/tag/v1.6.1	
> observiq-otel-collector-v1.6.0	observiq-otel-collector	v1.6.0 	true  	Aug 05, 2022	https://github.com/observIQ/observiq-otel-collector/releases/tag/v1.6.0	
> ```
> 
> Can `RELEASE DATE` be renamed to something that is one word? `RELEASE_DATE` or RELEASEDATE? Same with release notes. This would also mean reformatting the date values to something else. `08052022`, `08-05-2022`.
> 
> This would be useful if printing a column with awk.
> 
> ```shell
> bindplanectl get agent-versions | awk '{print $7}'
> ```

Changed to this:

```
NAME                          	TYPE                   	VERSION	PUBLIC	DATE      	URL
observiq-otel-collector-v1.6.1	observiq-otel-collector	v1.6.1 	true  	08-05-2022	https://github.com/observIQ/observiq-otel-collector/releases/tag/v1.6.1
observiq-otel-collector-v1.6.0	observiq-otel-collector	v1.6.0 	true  	08-05-2022	https://github.com/observIQ/observiq-otel-collector/releases/tag/v1.6.0
```

**Review by jsirianni — APPROVED** [review]

**Pull request merged**
